[tool.poetry]
name = "python3"
version = "0.1.0"
description = ""
authors = ["Jee Wan Gue <jeewangue@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pynvim = "^0.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
